version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "LouisBarranqueiro"
    groups:
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@fortawesome/fontawesome-free"
      development-dependencies:
        dependency-type: "development"
